table Calendar
	lineageTag: 13622c5b-db75-4abb-a6da-d3e950316d28

	column DateKey
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 6935e7de-8ffd-4171-bd42-5df8ed8b54e1
		summarizeBy: none
		sourceColumn: DateKey

		variation Variation
			isDefault
			relationship: 8ceaea55-e8a8-4f89-bfa0-c1d580cbd0e8
			defaultHierarchy: LocalDateTable_27c2bdb1-a10b-4918-96e4-6cdf3d64fa64.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column DateInt
		dataType: double
		isHidden
		lineageTag: d727c03e-3573-41e7-8eba-a6c709633b4d
		summarizeBy: sum
		sourceColumn: DateInt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthName
		dataType: string
		lineageTag: 4142290a-af28-405c-8733-5ac423981ba8
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column DayOfWeekName
		dataType: string
		lineageTag: 1db0865f-4e59-4dae-8263-f49d0b41fbf7
		summarizeBy: none
		sourceColumn: DayOfWeekName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: bd5db7cd-5659-4bc6-ba38-2f7907ad5311
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column QuarterOfYear
		dataType: int64
		formatString: 0
		lineageTag: bfa7d83b-80d6-461f-9bc1-7f1eb04409df
		summarizeBy: sum
		sourceColumn: QuarterOfYear

		annotation SummarizationSetBy = Automatic

	column MonthOfYear
		dataType: int64
		formatString: 0
		lineageTag: 3bdd14a2-3e41-474c-a25a-04bc622db8d6
		summarizeBy: sum
		sourceColumn: MonthOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: b00b9ea3-58df-4262-abc9-34e4a689e83f
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	partition Calendar-c5851a98-1654-4378-9576-8acf34cce5e3 = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimDate = Source{[Schema="",Item="DimDate"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(_DimDate,{{"YearKey", Int64.Type}, {"QuarterOfYear", Int64.Type}, {"MonthOfYear", Int64.Type}, {"DayOfMonth", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"MonthInCalendar", "QuarterInCalendar", "DayInWeek"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"YearKey", "Year"}})
				in
				    #"Renamed Columns"

	annotation ColumnsMetadata = {"Columns":[{"Name":"DateKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimDate.{DateKey,0}"},{"Name":"DateInt","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimDate.{DateInt,1}"},{"Name":"Year","Id":"Section1/DimDate/Changed Type.{YearKey,2}"},{"Name":"QuarterOfYear","Id":"Section1/DimDate/Changed Type.{QuarterOfYear,3}"},{"Name":"MonthOfYear","Id":"Section1/DimDate/Changed Type.{MonthOfYear,4}"},{"Name":"DayOfMonth","Id":"Section1/DimDate/Changed Type.{DayOfMonth,5}"},{"Name":"MonthName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimDate.{MonthName,6}"},{"Name":"DayOfWeekName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimDate.{DayOfWeekName,9}"}]}

	annotation PBI_ResultType = Table

