table Channel
	lineageTag: 94c9bd7e-0296-4dc3-9d21-b3e370276c6e

	column Channel
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3b72cdaa-3c3e-4cb4-9f9b-2483da3f8899
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column ChannelName
		dataType: string
		lineageTag: eb529d90-4f2b-445e-bc7e-a4bd00249700
		summarizeBy: none
		sourceColumn: ChannelName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Channel-3836f8fd-e2fe-46b4-9aa4-9956499fe1dc = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimChannel = Source{[Schema="",Item="DimChannel"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimChannel,{"ETLLoadID", "LoadDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ChannelKey", "Channel"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"ChannelLabel", "ChannelDescription", "UpdateDate"})
				in
				    #"Removed Columns1"

	annotation ColumnsMetadata = {"Columns":[{"Name":"Channel","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimChannel.{ChannelKey,0}"},{"Name":"ChannelName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimChannel.{ChannelName,2}"}]}

	annotation PBI_ResultType = Table

