table ProductCategory
	lineageTag: e3af3a27-7542-43f8-91b0-c94d6e0c7c72

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 06754f9c-3ba0-4785-b5ad-b3eacfc51601
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategory
		dataType: string
		lineageTag: bdf2953d-1fe8-4805-b2cf-ad6eefb3056f
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition ProductCategory-b82a23c6-fdce-4a34-a948-36a3255c445c = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimProductCategory = Source{[Schema="",Item="DimProductCategory"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimProductCategory,{"ProductCategoryLabel", "ETLLoadID", "LoadDate", "UpdateDate", "ProductCategoryDescription"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ProductCategoryName", "ProductCategory"}})
				in
				    #"Renamed Columns"

	annotation ColumnsMetadata = {"Columns":[{"Name":"ProductCategoryKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProductCategory.{ProductCategoryKey,0}"},{"Name":"ProductCategory","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProductCategory.{ProductCategoryName,2}"}]}

	annotation PBI_ResultType = Table

